version: "3"
services:
  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    environment:
      - address=61184328cfd30d8caa78438884d5322ce203c045 #derived from the private key which is passed in the args
      - bootnodeId=enr:-KO4QI8UTNgujUF_7JxoODFSlFfAJXiR3XSp5uoystrCw5GZM-e5esxgFGDyx709hbMsKBwbsqomGuN1kf_Xalx1MQiGAYUKcLXYg2V0aMfGhIcAEaWAgmlkgnY0gmlwhJ9Zw7uJc2VjcDI1NmsxoQIkeCWy-PKXcm3ORez6REDPtoDCE_joV261MNcL12CAeIRzbmFwwIN0Y3CCf5yDdWRwgn-c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=159.223.92.187
    build:
      context: .
      dockerfile: ./minerdeploy/Dockerfile
      args:
        privatekey: f8fe1be000009Ar3fv61fa753E809484fd6e6f8617b2F1dnjiub4b9666fD6f5
        password: 123456
    ports:
      - 8546:8545
    container_name: geth-miner-1
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address
    healthcheck:
      test: wget http://localhost:8546
      interval: 2s
      timeout: 5s
      retries: 30
networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
